customhost = "employee.cxu6wetzoblv.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "looichenyong-employee"
customregion = "us-east-1"
